# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moments of Insight
email: codesmith111@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have often wished to access the moments of insight
  that every one on this planet has had in their life.
  Those fleeting moments when we can see more clearly than we could before they happened;
  when we finally understand something, when our conceptual/mental
  model for things change and we surge forward on exciting journeys of
  discovery, understanding and creation. In this blog you will find some of my moments of insight;
  I would love to discover yours.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csmith111.github.io/" # the base hostname & protocol for your site
twitter_username: codesmith111
github_username:  csmith111

# Build settings
markdown: kramdown
